---
- name: Install the PAM package
  pacman:
    name: pambase
    state: present

- name: Ensure pam package is installed
  pacman:
    name: pam
    state: present

- name: Ensure /etc/security directory exists
  file:
    path: /etc/security
    state: directory
    mode: '0755'

- name: Ensure pwquality.conf exists
  file:
    path: /etc/security/pwquality.conf
    state: touch
    mode: '0644'

- name: Set password aging policy
  lineinfile:
    path: /etc/login.defs
    regexp: "^PASS_MAX_DAYS"
    line: "PASS_MAX_DAYS 90"

- name: Set password minimum age
  lineinfile:
    path: /etc/login.defs
    regexp: "^PASS_MIN_DAYS"
    line: "PASS_MIN_DAYS 10"

- name: Set password minimum length
  lineinfile:
    path: /etc/security/pwquality.conf
    regexp: "^#? *minlen ="
    line: "minlen = 12"
